### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by bdr99** [yugabyte/cqlsh#11]
It seems that Python 3.10 is unsupported.

This section of the wrapper script considers `3.10` to be unsupported because it is numerically less than `3.6`:
```sh
if [ "$version" = "3.6" ] || [ "$version" \> "3.6" ] || [ "$version" = "2.7" ]; then
    echo "supported"
else
    echo "unsupported"
fi
```

If I patch the script so that it considers 3.10 to be supported, then it instead fails with this error:
```
Traceback (most recent call last):
  File "C:\Work\Software\cqlsh\bin\ycqlsh.py", line 160, in <module>
    from cassandra.cluster import Cluster
  File "C:\Work\Software\cqlsh\bin\..\lib\cassandra-driver-internal-only-3.13.0.3-8d292edb.zip/cassandra-driver\3.13.0.3-8d292edb\cassandra\cluster.py", line 22, in <module>
ImportError: cannot import name 'Mapping' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)
```

**Comment by shyboylpf** [comment]
Suffering same issue, any updates here?

**Comment by ddorian** [comment]
Also posted here https://github.com/yugabyte/yugabyte-db/issues/16295

As a workaround, uou can specify the python binary manually like so:
```
CQLSH_PYTHON=/path/to/python/bin ./bin/ycqlsh
```
