### ISSUE TITLE
ycqlsh looks for `$(pwd)/\~/.cassandra/cqlshrc` due to lack of `os.path.expanduser()`

### ISSUE THREAD

**Issue by nodakai** [yugabyte/cqlsh#21]
https://github.com/yugabyte/cqlsh/blob/b86fd186e31b0720ec5da170ff81be65b452755f/bin/ycqlsh.py#L280

vs

https://github.com/yugabyte/cqlsh/blob/b86fd186e31b0720ec5da170ff81be65b452755f/bin/ycqlsh.py#L265

**Comment by HarshDaryani896** [comment]
Hey @nodakai, Thank you for pointing this out. We will take this up. You can track this using [#19754](https://github.com/yugabyte/yugabyte-db/issues/19754)
