### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by aegershman** [yugabyte/cqlsh#4]
I noticed in [yb 2.1.8.1 the release notes make mention of moving to python 3 for build and packaging scripts](https://github.com/yugabyte/yugabyte-db/releases/tag/v2.1.8.1), though I'm under the impression ycqlsh requires python 2.x. Any thoughts on whether ycqlsh will be able to leverage python 3? thanks all 👍

**Comment by mbautin** [comment]
@OlegLoginov could you please take a look at what was done in upstream cqlsh in https://issues.apache.org/jira/browse/CASSANDRA-10190 to support Python 3?

**Comment by aegershman** [comment]
Thanks all 👍  closing for tidyness
